name: juice-shop

services:
    juice-shop:
        image: bkimminich/juice-shop
        restart: unless-stopped
        network_mode: bridge
        ports:
            - target: 3000
              published: "3000"
              protocol: tcp

        volumes:
            - type: bind
              source: /DATA/AppData/juice-shop/config

x-casaos:
    main: juice-shop
    author: Lewis Parmenter
    category: Cyber Security
    developer: OWASP
    title:
        en_us: Juice Shop
    description:
        en_us: |
            Juice Shop is written in Node.js, Express and Angular. It was the first application written entirely in JavaScript listed in the OWASP VWA Directory.

            The application contains a vast number of hacking challenges of varying difficulty where the user is supposed to exploit the underlying vulnerabilities. The hacking progress is tracked on a score board. Finding this score board is actually one of the (easy) challenges!

            Apart from the hacker and awareness training use case, pentesting proxies or security scanners can use Juice Shop as a “guinea pig”-application to check how well their tools cope with JavaScript-heavy application frontends and REST APIs.
    
    architectures:
        - "386"
        - amd64
        - arm
        - arm64
        - ppc64le
    port_map: "3000"
    index: /